resources:

  # Tag for 8080 Firewall
  - name: allow-web-8080
    type: compute.v1.firewall
    properties:
      allowed:
        - IPProtocol: TCP
          ports:
            - '8080'
      description: "Allow port 8080 access to web servers"
      sourceRanges: ['0.0.0.0/0']
      targetTags: ['web-server-8080']

  # Service Account
  - name: service-account
    type: iam.v1.serviceAccount
    properties:
      accountId: hw10-sa
      displayName: hw10-sa

  # VM Web Server
  - name: webserver-vm
    type: compute.v1.instance
    properties:
      zone: us-east1-b
      machineType: zones/us-east1-b/machineTypes/e2-medium
      disks:
        - deviceName: boot
          type: PERSISTENT
          boot: true
          autoDelete: true
          initializeParams:
            sourceImage: projects/debian-cloud/global/images/family/debian-11
      networkInterfaces:
        - network: global/networks/default
      serviceAccounts:
        - email: hw10-sa@ds561-398719.iam.gserviceaccount.com
          scopes:
            - https://www.googleapis.com/auth/cloud-platform
      metadata:
        items:
          - key: startup-script
            value: |
              #! /bin/bash
              sudo systemctl enable hw10webserver
              sudo systemctl start hw10webserver
        dependsOn:
          - service-account
          - allow-web-8080
      tags:
        items:
          - web-server-8080


  # VM for Pub/Sub Listener
  - name: pubsub-listener-vm
    type: compute.v1.instance
    properties:
      zone: us-east1-b
      machineType: zones/us-east1-b/machineTypes/e2-medium
      disks:
        - deviceName: boot
          type: PERSISTENT
          boot: true
          autoDelete: true
          initializeParams:
            sourceImage: projects/debian-cloud/global/images/family/debian-11
      networkInterfaces:
        - network: global/networks/default
      serviceAccounts:
        - email: hw10-sa@ds561-398719.iam.gserviceaccount.com
          scopes:
            - https://www.googleapis.com/auth/pubsub
      metadata:
        dependsOn:
          - service-account


  # Cloud SQL Database
  - name: sql-database-instance
    type: sqladmin.v1beta4.instance
    properties:
      region: us-east1
      project: ds561-398719
      settings:
        tier: db-custom-4-16384

  # Pub/Sub Topic
  - name: hw10-topic
    type: gcp-types/pubsub-v1:projects.topics
    properties:
      topic: hw10-topic

  # Pub/Sub Subscription
  - name: hw10-sub
    type: gcp-types/pubsub-v1:projects.subscriptions
    properties:
      subscription: hw10-sub
      topic: projects/ds-561/topics/hw10-topic
    metadata:
      dependsOn:
        - hw10-topic
